### ISSUE TITLE
Is the database script added?

### ISSUE THREAD

**Issue by jrichardsz** [raguram1986/ragu#1]

**Comment by raguram1986** [comment]
hi

**Comment by raguram1986** [comment]
have you got my files sir

**Comment by jrichardsz** [comment]
yes. I see that mysql is required. Is a script required?

**Comment by raguram1986** [comment]
yes sir i upload the my sql fine now

**Comment by jrichardsz** [comment]
oks. Is this a kind of task? or is a job requirement?

**Comment by raguram1986** [comment]
i uploaded all files. i need the add,edit,update,delete the reocrds using spring boot and ajax
